services:
  - type: web
    name: adversight
    runtime: python
    buildCommand: pip install -r requirements.txt && python get_classes.py
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0